export const CREATE_GROUP = "CREATE_GROUP";
export const CREATE_GROUP_PENDING = "CREATE_GROUP_PENDING";
export const SHOW_GROUP_ERROR = "SHOW_GROUP_ERROR";
export const GET_USER_GROUPS = "GET_USER_GROUPS";
export const JOIN_GROUP = "JOIN_GROUP";
export const CURRENT_GROUP = "CURRENT_GROUP";