export const PATCH_USERNAME = "PATCH_USERNAME";
export const CHANGE_USERNAME_PENDING = "CHANGE_USERNAME_PENDING";

export const PATCH_PHONE = "PATCH_PHONE";
export const CHANGE_PHONE_PENDING = "CHANGE_PHONE_PENDING";

export const PATCH_BIO = "PATCH_BIO";
export const CHANGE_BIO_PENDING = "CHANGE_BIO_PENDING";

export const GET_USER_ERROR = 'GET_USER_ERROR';

export  const GET_USER = "GET_USER";
export  const GET_USER_PENDING = "GET_USER_PENDING";

export const LOGIN_PENDING = "LOGIN_PENDING";
export const SET_TOKEN = "SET_TOKEN";
export const SET_ID = "SET_ID";

export const LOGIN_BOOL = "LOGIN_BOOL";
export const CREATE_USER_PENDING = "CREATE_USER_PENDING";
export const LOGGEDINORNOT = "LOGGEDINORNOT";
export const SETS_USER_BIO = "SET_USER_BIO";
export const SETS_CURRENT_USER_BIO = "SETS_CURRENT_USER_BIO";
export const CREATE_OR_LOGIN = "CREATE_OR_LOGIN";